[build]
  publish = "build"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "max-age=604800, no-cache, public, must-revalidate"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    cache-control = "public, max-age=0, must-revalidate"
